CREATE TABLE IF NOT EXISTS users
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name  VARCHAR(300) UNIQUE                     NOT NULL,
    email VARCHAR(300) UNIQUE                     NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (id),
    CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS items
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY        NOT NULL,
    name        VARCHAR(300)                                   NOT NULL,
    description VARCHAR(1000)                                  NOT NULL,
    available   BOOLEAN,
    owner_id    BIGINT REFERENCES users (id) ON DELETE CASCADE NOT NULL,
    request_id  BIGINT REFERENCES requests (id) ON DELETE CASCADE NOT NULL,
    CONSTRAINT pk_item PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS requests
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY        NOT NULL,
    description  VARCHAR(1000)                                  NOT NULL,
    requestor_id BIGINT REFERENCES users (id) ON DELETE CASCADE NOT NULL,
    created      TIMESTAMP WITHOUT TIME ZONE                    NOT NULL,
    CONSTRAINT pk_request PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS comments
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY        NOT NULL,
    text      VARCHAR(1000)                                  NOT NULL,
    author_id BIGINT REFERENCES users (id) ON DELETE CASCADE NOT NULL,
    item_id   BIGINT REFERENCES items (id) ON DELETE CASCADE NOT NULL,
    created   TIMESTAMP WITHOUT TIME ZONE                    NOT NULL,
    CONSTRAINT pk_comment PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS bookings
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY        NOT NULL,
    start_time TIMESTAMP WITHOUT TIME ZONE                    NOT NULL,
    end_time   TIMESTAMP WITHOUT TIME ZONE                    NOT NULL,
    item_id    BIGINT REFERENCES items (id) ON DELETE CASCADE NOT NULL,
    booker_id  BIGINT REFERENCES users (id) ON DELETE CASCADE NOT NULL,
    status     VARCHAR(300)                                   NOT NULL,
    CONSTRAINT pk_booking PRIMARY KEY (id)
);